qca-wifi-host-cmn: Werror,-Wstrict-prototypes
drivers/staging/qca-wifi-host-cmn/target_if/core/src/target_if_main.c:81:40: error: a function declaration wit
hout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void

drivers/staging/qca-wifi-host-cmn/hif/src/ce/ce_service.c:2805:34: error: a function declaration without a pro
totype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void

drivers/staging/qca-wifi-host-cmn/wlan_cfg/wlan_cfg.c:292:49: error: a function declaration without a prototyp
e is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct wlan_cfg_dp_soc_ctxt *wlan_cfg_soc_attach()
                                                ^
                                                 void

Signed-off-by: NurKeinNeid <mralexman3000@gmail.com>